import { Inter, Roboto, Poppins, Montserrat, Source_Serif_4, Geist, Geist_Mono } from 'next/font/google'
import { Toaster } from 'react-hot-toast';
import "./globals.css";
import "./globals.scss";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const poppins = Poppins({
  variable: "--font-poppins",
  weight: ['100',"200", "400","500", "600"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${poppins.variable}`}
      >
        {children}
          <Toaster position="top-right" reverseOrder={false} />
      </body>
    </html>
  );
}
